/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/externalconsole1.xml
 */
using Types = sul.Externalconsole1.Types;

namespace sul.Externalconsole1
{

    public class KeepAlive : Packet
    {

        public const byte Id = 0;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public uint count;

        public KeepAlive() {}

        public KeepAlive(uint count)
        {
            this.count = count;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static KeepAlive FromBuffer(byte[] buffer)
        {
            var ret = new KeepAlive();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateNodes : Packet
    {

        public const byte Id = 1;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // action
        public const byte Add = 0;
        public const byte Remove = 1;

        public byte action;
        public string node;

        public UpdateNodes() {}

        public UpdateNodes(byte action, string node)
        {
            this.action = action;
            this.node = node;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateNodes FromBuffer(byte[] buffer)
        {
            var ret = new UpdateNodes();
            ret.decode(buffer);
            return ret;
        }

    }

    public class RequestStats : Packet
    {

        public const byte Id = 2;

        public const bool Clientbound = false;
        public const bool Serverbound = true;



        public RequestStats() {}

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static RequestStats FromBuffer(byte[] buffer)
        {
            var ret = new RequestStats();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateStats : Packet
    {

        public const byte Id = 3;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        public uint onlinePlayers;
        public uint maxPlayers;
        public uint uptime;
        public uint upload;
        public uint download;
        public Types.NodeStats[] nodes;

        public UpdateStats() {}

        public UpdateStats(uint onlinePlayers, uint maxPlayers, uint uptime, uint upload, uint download, Types.NodeStats[] nodes)
        {
            this.onlinePlayers = onlinePlayers;
            this.maxPlayers = maxPlayers;
            this.uptime = uptime;
            this.upload = upload;
            this.download = download;
            this.nodes = nodes;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateStats FromBuffer(byte[] buffer)
        {
            var ret = new UpdateStats();
            ret.decode(buffer);
            return ret;
        }

    }

}
