/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul.Utils
{

    public abstract class Stream
    {

        public virtual byte[] Encode()
        {
            var buffer = Buffer.Writer();
            EncodeImpl(buffer);
            return buffer.ToArray();
        }

        public virtual Stream Decode(byte[] _buffer)
        {
            var buffer = Buffer.Reader(_buffer);
            DecodeImpl(buffer);
            return this;
        }

        public virtual void EncodeBody(Buffer buffer)
        {
            EncodeImpl(buffer);
        }

        public virtual void DecodeBody(Buffer buffer)
        {
            DecodeImpl(buffer);
        }

        protected abstract void EncodeImpl(Buffer buffer);

        protected abstract void DecodeImpl(Buffer buffer);

    }

}
