/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
using System.Text;

using sul.Utils;
using sul.Hncom2.Types;

namespace sul.Hncom2.Login
{

    public class ConnectionRequest : sul.Utils.Packet
    {

        public const byte Id = 3;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint protocol;
        public string password;
        public string name;
        public bool main;

        public ConnectionRequest() : this(0, "", "", true) {}

        public ConnectionRequest(uint protocol, string password, string name, bool main)
        {
            this.protocol = protocol;
            this.password = password;
            this.name = name;
            this.main = main;
        }

        public override int GetId()
        {
            return (int)Id;
        }

        public override void EncodeId(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(sul.Utils.Buffer _buffer)
        {
            //_buffer.ReadUbyte();
        }

        protected override void EncodeImpl(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteVaruint(protocol);
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(password)); _buffer.WriteString(password);
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(name)); _buffer.WriteString(name);
            _buffer.WriteBool(main);
        }

        protected override void DecodeImpl(sul.Utils.Buffer _buffer)
        {
            //protocol = _buffer.ReadVaruint();
            //password = _buffer.ReadString();
            //name = _buffer.ReadString();
            //main = _buffer.ReadBool();
        }

        public static ConnectionRequest FromBuffer(byte[] buffer)
        {
            var ret = new ConnectionRequest();
            ret.Decode(buffer);
            return ret;
        }

    }

    public class ConnectionResponse : sul.Utils.Packet
    {

        public const byte Id = 4;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // status
        public const byte OK = 0;
        public const byte OUTDATED_HUB = 1;
        public const byte OUTDATED_NODE = 2;
        public const byte PASSWORD_REQUIRED = 3;
        public const byte WRONG_PASSWORD = 4;
        public const byte INVALID_NAME_LENGTH = 5;
        public const byte INVALID_NAME_CHARACTERS = 6;
        public const byte NAME_ALREADY_USED = 7;
        public const byte NAME_RESERVED = 8;

        public byte status;
        public uint protocol;

        public ConnectionResponse() : this(0, 0) {}

        public ConnectionResponse(byte status, uint protocol)
        {
            this.status = status;
            this.protocol = protocol;
        }

        public override int GetId()
        {
            return (int)Id;
        }

        public override void EncodeId(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(sul.Utils.Buffer _buffer)
        {
            //_buffer.ReadUbyte();
        }

        protected override void EncodeImpl(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteUbyte(status);
            if(status==1||status==2){ _buffer.WriteVaruint(protocol); }
        }

        protected override void DecodeImpl(sul.Utils.Buffer _buffer)
        {
            //status = _buffer.ReadUbyte();
            //if(status==1||status==2){ protocol = _buffer.ReadVaruint(); }
        }

        public static ConnectionResponse FromBuffer(byte[] buffer)
        {
            var ret = new ConnectionResponse();
            ret.Decode(buffer);
            return ret;
        }

    }

    public class HubInfo : sul.Utils.Packet
    {

        public const byte Id = 5;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // max
        public const int UNLIMITED = -1;

        public ulong time;
        public ulong serverId;
        public ulong reservedUuids;
        public string displayName;
        public GameInfo[] gamesInfo;
        public uint online;
        public int max;
        public string language;
        public string[] acceptedLanguages;
        public string additionalJson;

        public HubInfo() : this(0, 0, 0, "", new GameInfo[]{}, 0, 0, "", new string[]{}, "") {}

        public HubInfo(ulong time, ulong serverId, ulong reservedUuids, string displayName, GameInfo[] gamesInfo, uint online, int max, string language, string[] acceptedLanguages, string additionalJson)
        {
            this.time = time;
            this.serverId = serverId;
            this.reservedUuids = reservedUuids;
            this.displayName = displayName;
            this.gamesInfo = gamesInfo;
            this.online = online;
            this.max = max;
            this.language = language;
            this.acceptedLanguages = acceptedLanguages;
            this.additionalJson = additionalJson;
        }

        public override int GetId()
        {
            return (int)Id;
        }

        public override void EncodeId(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(sul.Utils.Buffer _buffer)
        {
            //_buffer.ReadUbyte();
        }

        protected override void EncodeImpl(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteVarulong(time);
            _buffer.WriteVarulong(serverId);
            _buffer.WriteVarulong(reservedUuids);
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(displayName)); _buffer.WriteString(displayName);
            _buffer.WriteVaruint(gamesInfo.Length); foreach (GameInfo gamesInfoChild in gamesInfo){ gamesInfoChild.EncodeBody(_buffer); }
            _buffer.WriteVaruint(online);
            _buffer.WriteVarint(max);
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(language)); _buffer.WriteString(language);
            _buffer.WriteVaruint(acceptedLanguages.Length); foreach (string acceptedLanguagesChild in acceptedLanguages){ _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(acceptedLanguagesChild)); _buffer.WriteString(acceptedLanguagesChild); }
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(additionalJson)); _buffer.WriteString(additionalJson);
        }

        protected override void DecodeImpl(sul.Utils.Buffer _buffer)
        {
            //time = _buffer.ReadVarulong();
            //serverId = _buffer.ReadVarulong();
            //reservedUuids = _buffer.ReadVarulong();
            //displayName = _buffer.ReadString();
            //gamesInfo.DecodeBody(_buffer);
            //online = _buffer.ReadVaruint();
            //max = _buffer.ReadVarint();
            //language = _buffer.ReadString();
            //acceptedLanguages.DecodeBody(_buffer);
            //additionalJson = _buffer.ReadString();
        }

        public static HubInfo FromBuffer(byte[] buffer)
        {
            var ret = new HubInfo();
            ret.Decode(buffer);
            return ret;
        }

    }

    public class NodeInfo : sul.Utils.Packet
    {

        public const byte Id = 6;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        // max
        public const uint UNLIMITED = 0;

        public ulong time;
        public uint max;
        public Game[] acceptedGames;
        public Plugin[] plugins;
        public string additionalJson;

        public NodeInfo() : this(0, 0, new Game[]{}, new Plugin[]{}, "") {}

        public NodeInfo(ulong time, uint max, Game[] acceptedGames, Plugin[] plugins, string additionalJson)
        {
            this.time = time;
            this.max = max;
            this.acceptedGames = acceptedGames;
            this.plugins = plugins;
            this.additionalJson = additionalJson;
        }

        public override int GetId()
        {
            return (int)Id;
        }

        public override void EncodeId(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(sul.Utils.Buffer _buffer)
        {
            //_buffer.ReadUbyte();
        }

        protected override void EncodeImpl(sul.Utils.Buffer _buffer)
        {
            _buffer.WriteVarulong(time);
            _buffer.WriteVaruint(max);
            _buffer.WriteVaruint(acceptedGames.Length); foreach (Game acceptedGamesChild in acceptedGames){ acceptedGamesChild.EncodeBody(_buffer); }
            _buffer.WriteVaruint(plugins.Length); foreach (Plugin pluginsChild in plugins){ pluginsChild.EncodeBody(_buffer); }
            _buffer.WriteVaruint(Encoding.UTF8.GetByteCount(additionalJson)); _buffer.WriteString(additionalJson);
        }

        protected override void DecodeImpl(sul.Utils.Buffer _buffer)
        {
            //time = _buffer.ReadVarulong();
            //max = _buffer.ReadVaruint();
            //acceptedGames.DecodeBody(_buffer);
            //plugins.DecodeBody(_buffer);
            //additionalJson = _buffer.ReadString();
        }

        public static NodeInfo FromBuffer(byte[] buffer)
        {
            var ret = new NodeInfo();
            ret.Decode(buffer);
            return ret;
        }

    }

}
