/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
using Types = sul.Hncom2.Types;

namespace sul.Hncom2
{

    public class Add : Packet
    {

        public const byte Id = 17;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // reason
        public const byte FirstJoin = 0;
        public const byte Transferred = 1;
        public const byte ForciblyTransferred = 2;

        // dimension
        public const byte Overworld = 0;
        public const byte Nether = 1;
        public const byte End = 2;

        // input mode
        public const byte Keyboard = 0;
        public const byte Touch = 1;
        public const byte Controller = 2;

        public uint hubId;
        public byte reason;
        public byte type;
        public uint protocol;
        public string version;
        public string username;
        public string displayName;
        public byte dimension;
        public uint viewDistance;
        public Types.Address clientAddress;
        public string serverAddress;
        public ushort serverPort;
        public Guid uuid;
        public Types.Skin skin;
        public string language;
        public byte inputMode;
        public uint latency;

        public Add() {}

        public Add(uint hubId, byte reason, byte type, uint protocol, string version, string username, string displayName, byte dimension, uint viewDistance, Types.Address clientAddress, string serverAddress, ushort serverPort, Guid uuid, Types.Skin skin, string language, byte inputMode, uint latency)
        {
            this.hubId = hubId;
            this.reason = reason;
            this.type = type;
            this.protocol = protocol;
            this.version = version;
            this.username = username;
            this.displayName = displayName;
            this.dimension = dimension;
            this.viewDistance = viewDistance;
            this.clientAddress = clientAddress;
            this.serverAddress = serverAddress;
            this.serverPort = serverPort;
            this.uuid = uuid;
            this.skin = skin;
            this.language = language;
            this.inputMode = inputMode;
            this.latency = latency;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static Add FromBuffer(byte[] buffer)
        {
            var ret = new Add();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Remove : Packet
    {

        public const byte Id = 18;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // reason
        public const byte Left = 0;
        public const byte TimedOut = 1;
        public const byte Kicked = 2;
        public const byte Transferred = 3;

        public uint hubId;
        public byte reason;

        public Remove() {}

        public Remove(uint hubId, byte reason)
        {
            this.hubId = hubId;
            this.reason = reason;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static Remove FromBuffer(byte[] buffer)
        {
            var ret = new Remove();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Kick : Packet
    {

        public const byte Id = 19;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string reason;
        public bool translation;
        public string[] parameters;

        public Kick() {}

        public Kick(uint hubId, string reason, bool translation, string[] parameters)
        {
            this.hubId = hubId;
            this.reason = reason;
            this.translation = translation;
            this.parameters = parameters;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static Kick FromBuffer(byte[] buffer)
        {
            var ret = new Kick();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Transfer : Packet
    {

        public const byte Id = 20;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        // on fail
        public const byte Disconnect = 0;
        public const byte Auto = 1;
        public const byte Reconnect = 2;

        public uint hubId;
        public uint node;
        public byte onFail;

        public Transfer() {}

        public Transfer(uint hubId, uint node, byte onFail)
        {
            this.hubId = hubId;
            this.node = node;
            this.onFail = onFail;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static Transfer FromBuffer(byte[] buffer)
        {
            var ret = new Transfer();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateDisplayName : Packet
    {

        public const byte Id = 21;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string displayName;

        public UpdateDisplayName() {}

        public UpdateDisplayName(uint hubId, string displayName)
        {
            this.hubId = hubId;
            this.displayName = displayName;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateDisplayName FromBuffer(byte[] buffer)
        {
            var ret = new UpdateDisplayName();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateWorld : Packet
    {

        public const byte Id = 22;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public uint world;

        public UpdateWorld() {}

        public UpdateWorld(uint hubId, uint world)
        {
            this.hubId = hubId;
            this.world = world;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateWorld FromBuffer(byte[] buffer)
        {
            var ret = new UpdateWorld();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateViewDistance : Packet
    {

        public const byte Id = 23;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public uint viewDistance;

        public UpdateViewDistance() {}

        public UpdateViewDistance(uint hubId, uint viewDistance)
        {
            this.hubId = hubId;
            this.viewDistance = viewDistance;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateViewDistance FromBuffer(byte[] buffer)
        {
            var ret = new UpdateViewDistance();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateLanguage : Packet
    {

        public const byte Id = 24;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string language;

        public UpdateLanguage() {}

        public UpdateLanguage(uint hubId, string language)
        {
            this.hubId = hubId;
            this.language = language;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateLanguage FromBuffer(byte[] buffer)
        {
            var ret = new UpdateLanguage();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateGamemode : Packet
    {

        public const byte Id = 25;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public uint hubId;
        public byte gamemode;

        public UpdateGamemode() {}

        public UpdateGamemode(uint hubId, byte gamemode)
        {
            this.hubId = hubId;
            this.gamemode = gamemode;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateGamemode FromBuffer(byte[] buffer)
        {
            var ret = new UpdateGamemode();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateInputMode : Packet
    {

        public const byte Id = 26;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // input mode
        public const byte Keyboard = 0;
        public const byte Touch = 1;
        public const byte Controller = 2;

        public uint hubId;
        public byte inputMode;

        public UpdateInputMode() {}

        public UpdateInputMode(uint hubId, byte inputMode)
        {
            this.hubId = hubId;
            this.inputMode = inputMode;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateInputMode FromBuffer(byte[] buffer)
        {
            var ret = new UpdateInputMode();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateLatency : Packet
    {

        public const byte Id = 27;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        public uint hubId;
        public uint latency;

        public UpdateLatency() {}

        public UpdateLatency(uint hubId, uint latency)
        {
            this.hubId = hubId;
            this.latency = latency;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdateLatency FromBuffer(byte[] buffer)
        {
            var ret = new UpdateLatency();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdatePacketLoss : Packet
    {

        public const byte Id = 28;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        public uint hubId;
        public float packetLoss;

        public UpdatePacketLoss() {}

        public UpdatePacketLoss(uint hubId, float packetLoss)
        {
            this.hubId = hubId;
            this.packetLoss = packetLoss;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static UpdatePacketLoss FromBuffer(byte[] buffer)
        {
            var ret = new UpdatePacketLoss();
            ret.decode(buffer);
            return ret;
        }

    }

    public class GamePacket : Packet
    {

        public const byte Id = 29;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public uint hubId;
        public byte[] packet;

        public GamePacket() {}

        public GamePacket(uint hubId, byte[] packet)
        {
            this.hubId = hubId;
            this.packet = packet;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static GamePacket FromBuffer(byte[] buffer)
        {
            var ret = new GamePacket();
            ret.decode(buffer);
            return ret;
        }

    }

    public class OrderedGamePacket : Packet
    {

        public const byte Id = 30;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public uint order;
        public byte[] packet;

        public OrderedGamePacket() {}

        public OrderedGamePacket(uint hubId, uint order, byte[] packet)
        {
            this.hubId = hubId;
            this.order = order;
            this.packet = packet;
        }

        public override int GetId()
        {
            return Id;
        }

        public override byte[] Encode()
        {
            return this._buffer;
        }

        public override void Decode(byte[] buffer)
        {
            this._buffer = buffer;
        }

        public static OrderedGamePacket FromBuffer(byte[] buffer)
        {
            var ret = new OrderedGamePacket();
            ret.decode(buffer);
            return ret;
        }

    }

}
