/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
using Types = sul.Hncom2.Types;

using Utils.Buffer;
using Utils.Packet;

namespace sul.Hncom2
{

    public class Uncompressed : Packet
    {

        public const byte Id = 1;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public byte[][] packets;

        public Uncompressed() {}

        public Uncompressed(byte[][] packets)
        {
            this.packets = packets;
        }

        public override int GetId()
        {
            return Id;
        }

        public override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        public override void EncodeImpl(Buffer _buffer)
        {
            foreach(byte[] packetsChild in packets){ foreach(byte packetsChildChild in packetsChild){ _buffer.WriteUbyte(packetsChildChild); } }
        }

        public override void DecodeImpl(Buffer _buffer)
        {

        }

        public static Uncompressed FromBuffer(byte[] buffer)
        {
            var ret = new Uncompressed();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Compressed : Packet
    {

        public const byte Id = 2;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public uint size;
        public byte[] payload;

        public Compressed() {}

        public Compressed(uint size, byte[] payload)
        {
            this.size = size;
            this.payload = payload;
        }

        public override int GetId()
        {
            return Id;
        }

        public override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        public override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        public override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(size);
            _buffer.WriteBytes(payload);
        }

        public override void DecodeImpl(Buffer _buffer)
        {


        }

        public static Compressed FromBuffer(byte[] buffer)
        {
            var ret = new Compressed();
            ret.decode(buffer);
            return ret;
        }

    }

}
