/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul.Utils
{

    public class About
    {

        public const string Website = "https://github.com/sel-project/sel-utils";

        public const int Version = 116;

    }

}
