/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul.Utils
{

    public abstract class LengthPrefixedType : Stream
    {

        public override void EncodeBody(Buffer buffer)
        {
            var _buffer = Buffer.Writer();
            EncodeImpl(_buffer);
            var encoded = _buffer.ToArray();
            EncodeLength(encoded.Length, buffer);
            buffer.WriteBytes(encoded);
        }

        public override void DecodeBody(Buffer buffer)
        {
            DecodeImpl(Buffer.Reader(buffer.ReadBytes(DecodeLength(buffer))));
        }

        protected abstract void EncodeLength(int length, Buffer buffer);

        protected abstract int DecodeLength(Buffer buffer);

    }

}
