/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
using Utils.Stream;

namespace Utils
{

    public abstract class LengthPrefixedType : Stream
    {

        public override void EncodeBody(Buffer buffer)
        {
            var _buffer = Buffer.Writer();
            EncodeImpl(_buffer);
            EncodeLength(_buffer.length, buffer);
            buffer.WriteBytes(_buffer.buffer);
        }

        public override void DecodeBody(Buffer buffer)
        {
            DecodeImpl(buffer.ReadBytes(DecodeLength(buffer)));
        }

        protected abstract void EncodeLength(int length, Buffer buffer);

        protected abstract int DecodeLength(Buffer buffer);

    }

}
