/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul.Utils
{

    public class Metadata : Stream
    {

        protected override void EncodeImpl(Buffer _buffer)
        {}

        protected override void DecodeImpl(Buffer _buffer)
        {}

    }

}
