/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul.Utils
{

    public abstract class Variant : Packet
    {

        private Packet packet;

        public Variant(Packet packet)
        {
            this.packet = packet;
        }

        public override int GetId()
        {
            return this.packet.GetId();
        }

        public override void EncodeId(Buffer buffer)
        {
            this.packet.EncodeId(buffer);
        }

        public override void DecodeId(Buffer buffer)
        {
            this.packet.DecodeId(buffer);
        }

    }

}
