/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle ("sel-utils")]
[assembly: AssemblyDescription ("Automatically generated libraries for Minecraft and Minecraft: Pocket Edition")]
[assembly: AssemblyVersion ("1.2.62")]
