/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom1.xml
 */
using Types = sul.Hncom1.Types;

using Utils.Buffer;
using Utils.Packet;

namespace sul.Hncom1
{

    public class Add : Packet
    {

        public const byte Id = 15;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // reason
        public const byte FirstJoin = 0;
        public const byte Transferred = 1;
        public const byte ForciblyTransferred = 2;

        // input mode
        public const byte Keyboard = 0;
        public const byte Touch = 1;
        public const byte Controller = 2;

        public uint hubId;
        public byte reason;
        public byte type;
        public uint protocol;
        public string version;
        public string username;
        public string displayName;
        public sbyte dimension;
        public uint viewDistance;
        public Types.Address clientAddress;
        public string serverAddress;
        public ushort serverPort;
        public Guid uuid;
        public Types.Skin skin;
        public string language;
        public byte inputMode;
        public uint latency;

        public Add() {}

        public Add(uint hubId, byte reason, byte type, uint protocol, string version, string username, string displayName, sbyte dimension, uint viewDistance, Types.Address clientAddress, string serverAddress, ushort serverPort, Guid uuid, Types.Skin skin, string language, byte inputMode, uint latency)
        {
            this.hubId = hubId;
            this.reason = reason;
            this.type = type;
            this.protocol = protocol;
            this.version = version;
            this.username = username;
            this.displayName = displayName;
            this.dimension = dimension;
            this.viewDistance = viewDistance;
            this.clientAddress = clientAddress;
            this.serverAddress = serverAddress;
            this.serverPort = serverPort;
            this.uuid = uuid;
            this.skin = skin;
            this.language = language;
            this.inputMode = inputMode;
            this.latency = latency;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteUbyte(reason);
            _buffer.WriteUbyte(type);
            _buffer.WriteVaruint(protocol);
            _buffer.WriteString(version);
            _buffer.WriteString(username);
            _buffer.WriteString(displayName);
            if(reason!=0){ _buffer.WriteByte(dimension); }
            if(reason!=0){ _buffer.WriteVaruint(viewDistance); }
            clientAddress.EncodeBody(_buffer);
            _buffer.WriteString(serverAddress);
            _buffer.WriteBigEndianUshort(serverPort);
            _buffer.WriteUuid(uuid);
            skin.EncodeBody(_buffer);
            _buffer.WriteString(language);
            _buffer.WriteUbyte(inputMode);
            _buffer.WriteVaruint(latency);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {







            if(reason!=0){  }
            if(reason!=0){  }








        }

        public static Add FromBuffer(byte[] buffer)
        {
            var ret = new Add();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Remove : Packet
    {

        public const byte Id = 16;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // reason
        public const byte Left = 0;
        public const byte TimedOut = 1;
        public const byte Kicked = 2;
        public const byte Transferred = 3;

        public uint hubId;
        public byte reason;

        public Remove() {}

        public Remove(uint hubId, byte reason)
        {
            this.hubId = hubId;
            this.reason = reason;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteUbyte(reason);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static Remove FromBuffer(byte[] buffer)
        {
            var ret = new Remove();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Kick : Packet
    {

        public const byte Id = 17;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string reason;
        public bool translation;
        public string[] parameters;

        public Kick() {}

        public Kick(uint hubId, string reason, bool translation, string[] parameters)
        {
            this.hubId = hubId;
            this.reason = reason;
            this.translation = translation;
            this.parameters = parameters;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteString(reason);
            _buffer.WriteBool(translation);
            if(translation==true){ foreach(string parametersChild in parameters){ _buffer.WriteString(parametersChild); } }
        }

        protected override void DecodeImpl(Buffer _buffer)
        {



            if(translation==true){  }
        }

        public static Kick FromBuffer(byte[] buffer)
        {
            var ret = new Kick();
            ret.decode(buffer);
            return ret;
        }

    }

    public class Transfer : Packet
    {

        public const byte Id = 18;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        // on fail
        public const byte Disconnect = 0;
        public const byte Auto = 1;
        public const byte Reconnect = 2;

        public uint hubId;
        public uint node;
        public byte onFail;

        public Transfer() {}

        public Transfer(uint hubId, uint node, byte onFail)
        {
            this.hubId = hubId;
            this.node = node;
            this.onFail = onFail;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteVaruint(node);
            _buffer.WriteUbyte(onFail);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {



        }

        public static Transfer FromBuffer(byte[] buffer)
        {
            var ret = new Transfer();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateDisplayName : Packet
    {

        public const byte Id = 19;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string displayName;

        public UpdateDisplayName() {}

        public UpdateDisplayName(uint hubId, string displayName)
        {
            this.hubId = hubId;
            this.displayName = displayName;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteString(displayName);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdateDisplayName FromBuffer(byte[] buffer)
        {
            var ret = new UpdateDisplayName();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateWorld : Packet
    {

        public const byte Id = 20;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string world;
        public sbyte dimension;

        public UpdateWorld() {}

        public UpdateWorld(uint hubId, string world, sbyte dimension)
        {
            this.hubId = hubId;
            this.world = world;
            this.dimension = dimension;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteString(world);
            _buffer.WriteByte(dimension);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {



        }

        public static UpdateWorld FromBuffer(byte[] buffer)
        {
            var ret = new UpdateWorld();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateViewDistance : Packet
    {

        public const byte Id = 21;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public uint viewDistance;

        public UpdateViewDistance() {}

        public UpdateViewDistance(uint hubId, uint viewDistance)
        {
            this.hubId = hubId;
            this.viewDistance = viewDistance;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteVaruint(viewDistance);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdateViewDistance FromBuffer(byte[] buffer)
        {
            var ret = new UpdateViewDistance();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateLanguage : Packet
    {

        public const byte Id = 22;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public string language;

        public UpdateLanguage() {}

        public UpdateLanguage(uint hubId, string language)
        {
            this.hubId = hubId;
            this.language = language;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteString(language);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdateLanguage FromBuffer(byte[] buffer)
        {
            var ret = new UpdateLanguage();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateInputMode : Packet
    {

        public const byte Id = 23;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        // input mode
        public const byte Keyboard = 0;
        public const byte Touch = 1;
        public const byte Controller = 2;

        public uint hubId;
        public byte inputMode;

        public UpdateInputMode() {}

        public UpdateInputMode(uint hubId, byte inputMode)
        {
            this.hubId = hubId;
            this.inputMode = inputMode;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteUbyte(inputMode);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdateInputMode FromBuffer(byte[] buffer)
        {
            var ret = new UpdateInputMode();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdateLatency : Packet
    {

        public const byte Id = 24;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        public uint hubId;
        public uint latency;

        public UpdateLatency() {}

        public UpdateLatency(uint hubId, uint latency)
        {
            this.hubId = hubId;
            this.latency = latency;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteVaruint(latency);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdateLatency FromBuffer(byte[] buffer)
        {
            var ret = new UpdateLatency();
            ret.decode(buffer);
            return ret;
        }

    }

    public class UpdatePacketLoss : Packet
    {

        public const byte Id = 25;

        public const bool Clientbound = true;
        public const bool Serverbound = false;

        public uint hubId;
        public float packetLoss;

        public UpdatePacketLoss() {}

        public UpdatePacketLoss(uint hubId, float packetLoss)
        {
            this.hubId = hubId;
            this.packetLoss = packetLoss;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteBigEndianFloat(packetLoss);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static UpdatePacketLoss FromBuffer(byte[] buffer)
        {
            var ret = new UpdatePacketLoss();
            ret.decode(buffer);
            return ret;
        }

    }

    public class GamePacket : Packet
    {

        public const byte Id = 26;

        public const bool Clientbound = true;
        public const bool Serverbound = true;

        public uint hubId;
        public byte[] packet;

        public GamePacket() {}

        public GamePacket(uint hubId, byte[] packet)
        {
            this.hubId = hubId;
            this.packet = packet;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteBytes(packet);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {


        }

        public static GamePacket FromBuffer(byte[] buffer)
        {
            var ret = new GamePacket();
            ret.decode(buffer);
            return ret;
        }

    }

    public class OrderedGamePacket : Packet
    {

        public const byte Id = 27;

        public const bool Clientbound = false;
        public const bool Serverbound = true;

        public uint hubId;
        public uint order;
        public byte[] packet;

        public OrderedGamePacket() {}

        public OrderedGamePacket(uint hubId, uint order, byte[] packet)
        {
            this.hubId = hubId;
            this.order = order;
            this.packet = packet;
        }

        public override int GetId()
        {
            return Id;
        }

        protected override void EncodeId(Buffer _buffer)
        {
            _buffer.WriteUbyte(Id);
        }

        protected override void DecodeId(Buffer _buffer)
        {
            _buffer.ReadUbyte();
        }

        protected override void EncodeImpl(Buffer _buffer)
        {
            _buffer.WriteVaruint(hubId);
            _buffer.WriteVaruint(order);
            _buffer.WriteBytes(packet);
        }

        protected override void DecodeImpl(Buffer _buffer)
        {



        }

        public static OrderedGamePacket FromBuffer(byte[] buffer)
        {
            var ret = new OrderedGamePacket();
            ret.decode(buffer);
            return ret;
        }

    }

}
